version: '3.6'

services:
  postgres:
    image: postgres
    hostname: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=botan

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
