version: '3.6'

services:
  botan:
    image: botan
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GITHUB_SHA
        - VERSION=0.1.0
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_CONNECTION_STRING=Host = postgres; User Id = postgres; Password = postgres; Database = botan; Port = 5432
      - JWT_PASS_PHRASE=IcHog0qHdSZJlKvCjL/5CfDONW7CC749vaPuiU1eTAY=

  postgres:
    image: postgres
    hostname: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=botan

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
