### Add university
POST 127.0.0.1:8080/universities
Content-Type: application/json

{
  "Name": "Kryvyi Rih National University"
}

### Add category
POST 127.0.0.1:8080/categories
Content-Type: application/json

{
  "Name": "MPZ department"
}

### Add a question
POST 127.0.0.1:8080/questions
Content-Type: application/json

{
  "Title": "Find minim value in an array",
  "University": "6304e572cd3ff938236afcc3",
  "Category": "6304e7e45e5be5d5fdd1e60e",
  "Description": "Description"
}

### Add an answer to a question
POST 127.0.0.1:8080/questions/6308d567326034b55f620d11/answers
Content-Type: application/json

{
  "Code": "Code",
  "Language": "CSharp"
}

### Get question by id
GET 127.0.0.1:8080/questions/6308d567326034b55f620d11
Content-Type: application/json

### Get all questions
GET 127.0.0.1:8080/questions
Content-Type: application/json