name: build

on:
  push:
    branches:
    tags:
    paths:
      - ".github/workflows/ci-build.yml"
      - "backend/**"
      - "frontend/apps/**"
      - ".dockerignore"
      - "Dockerfile"
      - "!**.md"
      - "!frontend/packages/**"
  pull_request:
    paths:
      - ".github/workflows/ci-build.yml"
      - "backend/**"
      - "frontend/apps/**"
      - ".dockerignore"
      - "Dockerfile"
      - "!**.md"
      - "!frontend/packages/**"

jobs:
  build-images:
    name: Build Docker images
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      
      - name: install .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.x.x

      - name: restore .NET tools
        run: dotnet tool restore

      - name: build docker image without pushing (only outside master)
        if: ${{ github.ref != 'refs/heads/master' }}
        run: |
          version="$(dotnet gitversion /showvariable SemVer)" 
          docker buildx build --build-arg VERSION=${version}

      - name: build and deploy master image to ghcr.io
        if: ${{ github.ref == 'refs/heads/master' }}
        env:
          GITHUB_PACKAGE_TOKEN: ${{ secrets.PKG_TOKEN }}
          USERNAME: ${{ github.actor }}
          GITHUB_SHA: ${{ github.sha}}
          GITHUB_REF: ${{ github.ref}}
        run: |
          version="$(dotnet gitversion /showvariable SemVer)" 
          echo "GITHUB_SHA=${GITHUB_SHA}"
          echo ${GITHUB_PACKAGE_TOKEN} | docker login ghcr.io -u ${USERNAME} --password-stdin
          docker buildx build --push \
              --build-arg GITHUB_SHA=${GITHUB_SHA} --build-arg VERSION=${version} \
              -t ghcr.io/yurii-hunter/botan:${version} .

      - name: deploy tagged (latest) to ghcr.io
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        env:
          GITHUB_PACKAGE_TOKEN: ${{ secrets.PKG_TOKEN }}
          USERNAME: ${{ github.actor }}
          GITHUB_SHA: ${{ github.sha}}
          GITHUB_REF: ${{ github.ref}}
        run: |
          version="$(dotnet gitversion /showvariable SemVer)"
          echo "VERSION=${version}"
          echo "GITHUB_SHA=${GITHUB_SHA}"
          echo ${GITHUB_PACKAGE_TOKEN} | docker login ghcr.io -u ${USERNAME} --password-stdin
          docker buildx build --push \
              --build-arg GITHUB_SHA=${GITHUB_SHA} --build-arg VERSION=${version} \
              -t ghcr.io/yurii-hunter/botan:${version} -t ghcr.io/yurii-hunter/botan:latest .